@echo off
echo Removing all frontend artefacts generated by Vaadin ...
del \\?\%~dp0package.json /q 2>nul
del \\?\%~dp0package-lock.json /q 2>nul
del \\?\%~dp0webpack.config.js /q 2>nul
del \\?\%~dp0webpack.generated.js /q 2>nul
del \\?\%~dp0pnpmfile.js /q 2>nul
del \\?\%~dp0pnpm-lock.yaml /q 2>nul
rmdir \\?\%~dp0node_modules /q /s 2>nul
rmdir \\?\%~dp0target\frontend /q /s 2>nul
echo ... done
echo.
pause
